---
- name: Prometheus role
  hosts: monitoring
  become: yes
  tags: prometheus
  roles:
    - role: cloudalchemy.prometheus
      vars:
        prometheus_alert_rules: []
        prometheus_alertmanager_config:
          - scheme: http
            static_configs:
              - targets:
                - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9093"
   
- name: AlertManager role
  hosts: monitoring
  become: yes
  tags: alertmanager
  roles:
    - role: cloudalchemy.alertmanager
      vars:
        alertmanager_route:
          group_by: [job]
          receiver: default
        alertmanager_receivers:
          - name: default
            webhook_configs:
            - send_resolved: True
              url: http://localhost:9087/alert/-chatid
          
- name: Grafana role
  hosts: monitoring
  become: yes
  tags: grafana
  roles:
    - role: cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: SecretIsMyPass
        grafana_users:
          allow_sign_up: false
          auto_assign_org_role: Viewer
          default_theme: dark 
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: "http://{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
            basicAuth: false  
        grafana_metrics:
          enabled: true
        grafana_dashboards:
          - dashboard_id: 9628 # Postgres Dashboard
            revision_id: 4
            datasource: prometheus
          - dashboard_id: 1860 # Node Dashboard
            revision_id: 20
            datasource: prometheus
          - dashboard_id: 11074 # Node Dashboard
            revision_id: 2
            datasource: prometheus

- name: Node exporter role
  hosts: node
  become: yes
  tags: node
  roles:
    - cloudalchemy.node-exporter

- name: Postgres exporter role
  hosts: postgres
  become: yes
  tags: postgres
  roles:
    - ome.postgres-exporter